### ISSUE TITLE
bad

### ISSUE THREAD

**Issue by simplyplu** [orphanlol/Nosama#3]
got me banned :-(

**Comment by orphanlol** [comment]
real!!!?!?!?!??!??!

**Comment by notplu** [comment]
i swaer!!1!1

**Comment by orphanlol** [comment]
how to maek real iready hac??!?!?!?!!??!?!?!?!?! without rob waldron1@#?!?#!@?#?#!?@?#!

**Comment by notplu** [comment]
THERE IS NO WAY..........

**Comment by orphanlol** [comment]
how to maccc hacc (pls tell)

> THERE IS NO WAY..........
also what do u mean
